import {
  Sparkles,
  Receipt,
  Bell,
  CheckCircle2,
  AlertTriangle,
  Clock3,
  XCircle,
  Cake,
  PartyPopper,
  Trophy,
  CalendarClock,
  Gift,
  RotateCcw,
} from 'lucide-react'

// ─── Storage ──────────────────────────────────────────────────────────────────

const STORAGE_KEY = 'repeat_memberships'

export function genMembershipId() {
  return Math.random().toString(36).slice(2) + Date.now().toString(36)
}

// ─── Seed data ──────────────────────────────────────────────────────────────────
// Datos de ejemplo para que el módulo tenga contenido real desde el primer render.
// "Hoy" para efectos de las fechas de ejemplo: 2026-08-03.

const SEED_PLANS = [
  {
    id: 'plan_basico',
    name: 'Básico',
    description: 'Acceso a beneficios esenciales. Ideal para empezar.',
    active: true,
    billing_period_days: 30,
    price: 9990,
    trial_days: 7,
    renewal_frequency: 'monthly',
    included_services: [{ name: '1 corte al mes' }],
    included_products: [],
    discount_pct: 10,
    point_multiplier: 1,
    welcome_reward: 'Corte de bienvenida gratis',
    renewal_reward: null,
    perks: [],
    cancellation_policy: 'anytime',
    allow_pause: true,
    member_limit: null,
    color: '#6b7280',
  },
  {
    id: 'plan_plus',
    name: 'Plus',
    description: 'Para clientes frecuentes que quieren más beneficios y prioridad.',
    active: true,
    billing_period_days: 30,
    price: 17990,
    trial_days: 7,
    renewal_frequency: 'monthly',
    included_services: [{ name: '2 cortes al mes' }, { name: 'Arreglo de barba' }],
    included_products: [{ name: 'Cera para barba' }],
    discount_pct: 15,
    point_multiplier: 2,
    welcome_reward: 'Arreglo de barba gratis',
    renewal_reward: '10% off en tu próxima renovación',
    perks: [{ name: 'Reserva prioritaria' }, { name: 'Bebida de cortesía' }],
    cancellation_policy: 'anytime',
    allow_pause: true,
    member_limit: null,
    color: '#f59e0b',
  },
  {
    id: 'plan_vip',
    name: 'VIP',
    description: 'La experiencia completa: barbero fijo, eventos y kit de grooming.',
    active: true,
    billing_period_days: 30,
    price: 29990,
    trial_days: 0,
    renewal_frequency: 'monthly',
    included_services: [{ name: 'Cortes ilimitados' }, { name: 'Arreglo de barba' }, { name: 'Tratamiento capilar' }],
    included_products: [{ name: 'Kit de grooming trimestral' }],
    discount_pct: 25,
    point_multiplier: 3,
    welcome_reward: 'Kit de bienvenida premium',
    renewal_reward: 'Servicio gratis cada 3 renovaciones',
    perks: [{ name: 'Barbero fijo asignado' }, { name: 'Acceso a eventos exclusivos' }],
    cancellation_policy: 'end_of_period',
    allow_pause: true,
    member_limit: 50,
    color: '#111827',
  },
]

const SEED_MEMBERS = [
  {
    id: 'mem_1',
    name: 'Camila Rossi',
    email: 'camila.rossi@example.com',
    avatar_url: null,
    plan_id: 'plan_plus',
    status: 'active',
    joined_at: '2026-02-03',
    renewal_date: '2026-08-10',
    total_spent: 143920,
    lifetime_value: 172700,
    last_visit: '2026-07-28',
    visit_frequency: '1x por semana',
    payment_history: [
      { date: '2026-07-10', amount: 17990, status: 'paid' },
      { date: '2026-06-10', amount: 17990, status: 'paid' },
      { date: '2026-05-10', amount: 17990, status: 'paid' },
    ],
    renewal_history: [
      { date: '2026-07-10', plan_name: 'Plus', amount: 17990 },
      { date: '2026-06-10', plan_name: 'Plus', amount: 17990 },
    ],
    visit_history: [
      { date: '2026-07-28', service: 'Corte + arreglo de barba' },
      { date: '2026-07-14', service: 'Corte clásico' },
      { date: '2026-07-01', service: 'Corte + arreglo de barba' },
    ],
    rewards_earned: [
      { name: 'Arreglo de barba gratis', date: '2026-02-03' },
      { name: '10% off renovación', date: '2026-06-10' },
    ],
    wallet_balance: 40,
    services_used: [
      { name: 'Corte clásico', count: 6 },
      { name: 'Arreglo de barba', count: 5 },
    ],
    favorite_product: 'Cera para barba',
    favorite_employee: 'Diego',
    communication_timeline: [
      { date: '2026-02-03', channel: 'push', message: 'Bienvenida a Barber Club Plus' },
      { date: '2026-08-03', channel: 'push', message: 'Tu membresía se renueva en 7 días' },
    ],
    suggested_actions: ['Se vence en 7 días — enviar recordatorio de renovación'],
  },
  {
    id: 'mem_2',
    name: 'Martín Guzmán',
    email: 'martin.guzman@example.com',
    avatar_url: null,
    plan_id: 'plan_vip',
    status: 'active',
    joined_at: '2025-11-15',
    renewal_date: '2026-09-15',
    total_spent: 269910,
    lifetime_value: 359880,
    last_visit: '2026-08-01',
    visit_frequency: '2x por semana',
    payment_history: [
      { date: '2026-07-15', amount: 29990, status: 'paid' },
      { date: '2026-06-15', amount: 29990, status: 'paid' },
    ],
    renewal_history: [{ date: '2026-07-15', plan_name: 'VIP', amount: 29990 }],
    visit_history: [
      { date: '2026-08-01', service: 'Corte + tratamiento capilar' },
      { date: '2026-07-29', service: 'Corte clásico' },
      { date: '2026-07-25', service: 'Arreglo de barba' },
    ],
    rewards_earned: [{ name: 'Kit de bienvenida premium', date: '2025-11-15' }],
    wallet_balance: 120,
    services_used: [
      { name: 'Corte clásico', count: 18 },
      { name: 'Tratamiento capilar', count: 4 },
    ],
    favorite_product: 'Shampoo anticaída',
    favorite_employee: 'Bruno',
    communication_timeline: [{ date: '2025-11-15', channel: 'push', message: 'Bienvenida a Barber Club VIP' }],
    suggested_actions: [],
  },
  {
    id: 'mem_3',
    name: 'Sofía Bianchi',
    email: 'sofia.bianchi@example.com',
    avatar_url: null,
    plan_id: 'plan_basico',
    status: 'active',
    joined_at: '2026-06-01',
    renewal_date: '2026-09-01',
    total_spent: 19980,
    lifetime_value: 23980,
    last_visit: '2026-07-20',
    visit_frequency: '1x por mes',
    payment_history: [
      { date: '2026-07-01', amount: 9990, status: 'paid' },
      { date: '2026-06-01', amount: 9990, status: 'paid' },
    ],
    renewal_history: [{ date: '2026-07-01', plan_name: 'Básico', amount: 9990 }],
    visit_history: [
      { date: '2026-07-20', service: 'Corte clásico' },
      { date: '2026-06-18', service: 'Corte clásico' },
    ],
    rewards_earned: [{ name: 'Corte de bienvenida gratis', date: '2026-06-01' }],
    wallet_balance: 10,
    services_used: [{ name: 'Corte clásico', count: 2 }],
    favorite_product: null,
    favorite_employee: 'Fede',
    communication_timeline: [{ date: '2026-06-01', channel: 'push', message: 'Bienvenida a Barber Club Básico' }],
    suggested_actions: ['No usó su beneficio de corte gratis este mes'],
  },
  {
    id: 'mem_4',
    name: 'Nicolás Ferro',
    email: 'nicolas.ferro@example.com',
    avatar_url: null,
    plan_id: 'plan_plus',
    status: 'active',
    joined_at: '2026-01-10',
    renewal_date: '2026-08-10',
    total_spent: 125930,
    lifetime_value: 150000,
    last_visit: '2026-07-30',
    visit_frequency: '1x por semana',
    payment_history: [
      { date: '2026-07-10', amount: 17990, status: 'paid' },
      { date: '2026-06-10', amount: 17990, status: 'failed' },
      { date: '2026-06-12', amount: 17990, status: 'paid' },
    ],
    renewal_history: [{ date: '2026-07-10', plan_name: 'Plus', amount: 17990 }],
    visit_history: [
      { date: '2026-07-30', service: 'Corte + arreglo de barba' },
      { date: '2026-07-16', service: 'Corte clásico' },
    ],
    rewards_earned: [{ name: 'Arreglo de barba gratis', date: '2026-01-10' }],
    wallet_balance: 55,
    services_used: [
      { name: 'Corte clásico', count: 9 },
      { name: 'Arreglo de barba', count: 7 },
    ],
    favorite_product: 'Pomada mate',
    favorite_employee: 'Diego',
    communication_timeline: [
      { date: '2026-01-10', channel: 'push', message: 'Bienvenida a Barber Club Plus' },
      { date: '2026-06-10', channel: 'email', message: 'Tu pago no pudo procesarse' },
    ],
    suggested_actions: ['Se vence en 7 días — enviar recordatorio de renovación'],
  },
  {
    id: 'mem_5',
    name: 'Lucía Medina',
    email: 'lucia.medina@example.com',
    avatar_url: null,
    plan_id: 'plan_basico',
    status: 'expired',
    joined_at: '2025-09-01',
    renewal_date: '2026-07-01',
    total_spent: 79920,
    lifetime_value: 79920,
    last_visit: '2026-06-25',
    visit_frequency: '1x por mes',
    payment_history: [
      { date: '2026-06-01', amount: 9990, status: 'paid' },
      { date: '2026-05-01', amount: 9990, status: 'paid' },
    ],
    renewal_history: [{ date: '2026-06-01', plan_name: 'Básico', amount: 9990 }],
    visit_history: [{ date: '2026-06-25', service: 'Corte clásico' }],
    rewards_earned: [{ name: 'Corte de bienvenida gratis', date: '2025-09-01' }],
    wallet_balance: 0,
    services_used: [{ name: 'Corte clásico', count: 8 }],
    favorite_product: null,
    favorite_employee: 'Fede',
    communication_timeline: [{ date: '2026-07-01', channel: 'push', message: 'Tu membresía venció' }],
    suggested_actions: ['Membresía vencida — enviar campaña de win-back'],
  },
  {
    id: 'mem_6',
    name: 'Emiliano Suárez',
    email: 'emiliano.suarez@example.com',
    avatar_url: null,
    plan_id: 'plan_vip',
    status: 'cancelled',
    joined_at: '2025-05-01',
    renewal_date: null,
    total_spent: 359880,
    lifetime_value: 359880,
    last_visit: '2026-06-10',
    visit_frequency: 'Sin actividad reciente',
    cancellation_reason: 'No usaba el beneficio',
    payment_history: [{ date: '2026-06-01', amount: 29990, status: 'paid' }],
    renewal_history: [{ date: '2026-06-01', plan_name: 'VIP', amount: 29990 }],
    visit_history: [{ date: '2026-06-10', service: 'Corte clásico' }],
    rewards_earned: [{ name: 'Kit de bienvenida premium', date: '2025-05-01' }],
    wallet_balance: 30,
    services_used: [{ name: 'Corte clásico', count: 22 }],
    favorite_product: 'Shampoo anticaída',
    favorite_employee: 'Bruno',
    communication_timeline: [{ date: '2026-06-15', channel: 'email', message: 'Cancelaste tu membresía VIP' }],
    suggested_actions: ['Cancelado hace poco — buen candidato para campaña de reactivación'],
  },
  {
    id: 'mem_7',
    name: 'Tomás Ibarra',
    email: 'tomas.ibarra@example.com',
    avatar_url: null,
    plan_id: 'plan_plus',
    status: 'paused',
    joined_at: '2026-03-01',
    renewal_date: '2026-08-20',
    total_spent: 89950,
    lifetime_value: 107940,
    last_visit: '2026-06-15',
    visit_frequency: 'Pausado',
    payment_history: [{ date: '2026-06-01', amount: 17990, status: 'paid' }],
    renewal_history: [{ date: '2026-06-01', plan_name: 'Plus', amount: 17990 }],
    visit_history: [{ date: '2026-06-15', service: 'Corte + arreglo de barba' }],
    rewards_earned: [{ name: 'Arreglo de barba gratis', date: '2026-03-01' }],
    wallet_balance: 25,
    services_used: [{ name: 'Corte clásico', count: 5 }],
    favorite_product: null,
    favorite_employee: 'Diego',
    communication_timeline: [{ date: '2026-06-20', channel: 'push', message: 'Pausaste tu membresía' }],
    suggested_actions: ['Pausado — recordar reactivación antes del 20 de agosto'],
  },
  {
    id: 'mem_8',
    name: 'Valentina Cruz',
    email: 'valentina.cruz@example.com',
    avatar_url: null,
    plan_id: 'plan_vip',
    status: 'active',
    joined_at: '2024-12-01',
    renewal_date: '2026-12-01',
    total_spent: 599800,
    lifetime_value: 899700,
    last_visit: '2026-08-02',
    visit_frequency: '3x por semana',
    payment_history: [
      { date: '2026-07-01', amount: 29990, status: 'paid' },
      { date: '2026-06-01', amount: 29990, status: 'paid' },
    ],
    renewal_history: [
      { date: '2026-07-01', plan_name: 'VIP', amount: 29990 },
      { date: '2026-06-01', plan_name: 'VIP', amount: 29990 },
    ],
    visit_history: [
      { date: '2026-08-02', service: 'Corte + tratamiento capilar' },
      { date: '2026-07-30', service: 'Corte clásico' },
      { date: '2026-07-28', service: 'Arreglo de barba' },
    ],
    rewards_earned: [
      { name: 'Kit de bienvenida premium', date: '2024-12-01' },
      { name: 'Servicio gratis (3 renovaciones)', date: '2026-03-01' },
    ],
    wallet_balance: 210,
    services_used: [
      { name: 'Corte clásico', count: 40 },
      { name: 'Tratamiento capilar', count: 10 },
    ],
    favorite_product: 'Kit de grooming premium',
    favorite_employee: 'Bruno',
    communication_timeline: [{ date: '2024-12-01', channel: 'push', message: 'Bienvenida a Barber Club VIP' }],
    suggested_actions: ['Cliente top — candidata a programa de referidos'],
  },
  // Cancelados adicionales, con motivo, para poder graficar "razones de cancelación" con datos reales.
  {
    id: 'mem_9',
    name: 'Rocío Paredes',
    email: 'rocio.paredes@example.com',
    avatar_url: null,
    plan_id: 'plan_plus',
    status: 'cancelled',
    joined_at: '2026-01-05',
    renewal_date: null,
    total_spent: 53970,
    lifetime_value: 53970,
    last_visit: '2026-05-20',
    visit_frequency: 'Sin actividad reciente',
    cancellation_reason: 'Precio muy alto',
    payment_history: [{ date: '2026-05-01', amount: 17990, status: 'paid' }],
    renewal_history: [{ date: '2026-05-01', plan_name: 'Plus', amount: 17990 }],
    visit_history: [{ date: '2026-05-20', service: 'Corte clásico' }],
    rewards_earned: [{ name: 'Arreglo de barba gratis', date: '2026-01-05' }],
    wallet_balance: 5,
    services_used: [{ name: 'Corte clásico', count: 3 }],
    favorite_product: null,
    favorite_employee: 'Fede',
    communication_timeline: [{ date: '2026-05-25', channel: 'email', message: 'Cancelaste tu membresía Plus' }],
    suggested_actions: ['Canceló por precio — ofrecer plan Básico en la campaña de recuperación'],
  },
  {
    id: 'mem_10',
    name: 'Federico Aguirre',
    email: 'federico.aguirre@example.com',
    avatar_url: null,
    plan_id: 'plan_basico',
    status: 'cancelled',
    joined_at: '2025-08-01',
    renewal_date: null,
    total_spent: 89910,
    lifetime_value: 89910,
    last_visit: '2026-04-02',
    visit_frequency: 'Sin actividad reciente',
    cancellation_reason: 'Se mudó de ciudad',
    payment_history: [{ date: '2026-04-01', amount: 9990, status: 'paid' }],
    renewal_history: [{ date: '2026-04-01', plan_name: 'Básico', amount: 9990 }],
    visit_history: [{ date: '2026-04-02', service: 'Corte clásico' }],
    rewards_earned: [{ name: 'Corte de bienvenida gratis', date: '2025-08-01' }],
    wallet_balance: 0,
    services_used: [{ name: 'Corte clásico', count: 9 }],
    favorite_product: null,
    favorite_employee: 'Diego',
    communication_timeline: [{ date: '2026-04-10', channel: 'email', message: 'Cancelaste tu membresía Básico' }],
    suggested_actions: [],
  },
]

// ─── Automatizaciones ──────────────────────────────────────────────────────────
// Igual patrón que las automatizaciones de notificaciones ya existentes en el resto
// de la app (ver NotificationsMoonCafe.jsx / ComunicacionRoadmap.jsx): tarjeta con
// trigger + copy de ejemplo editable. Los íconos/definiciones NO se persisten (no son
// serializables); solo el estado editable (enabled/header/body/extra.value) vive en
// el localStorage compartido, y se mergea en runtime con esta definición por `id`.
export const AUTOMATION_DEFINITIONS = [
  {
    id: 'welcome',
    icon: Sparkles,
    color: 'bg-amber-100 dark:bg-amber-900 text-amber-600 dark:text-amber-400',
    accent: 'border-amber-300',
    title: 'Bienvenida',
    description: 'Se envía cuando un cliente se suscribe a un plan.',
    extraLabel: null,
  },
  {
    id: 'purchase_confirmed',
    icon: Receipt,
    color: 'bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-400',
    accent: 'border-blue-300',
    title: 'Membresía comprada',
    description: 'Se envía como comprobante inmediato de la compra del plan.',
    extraLabel: null,
  },
  {
    id: 'renewal_reminder',
    icon: Bell,
    color: 'bg-violet-100 dark:bg-violet-900 text-violet-600 dark:text-violet-400',
    accent: 'border-violet-300',
    title: 'Recordatorio de renovación',
    description: 'Se envía N días antes de la próxima renovación.',
    extraLabel: 'Días antes de la renovación',
  },
  {
    id: 'renewal_successful',
    icon: CheckCircle2,
    color: 'bg-emerald-100 dark:bg-emerald-900 text-emerald-600 dark:text-emerald-400',
    accent: 'border-emerald-300',
    title: 'Renovación exitosa',
    description: 'Se envía cuando el cobro de la renovación se procesa correctamente.',
    extraLabel: null,
  },
  {
    id: 'payment_failed',
    icon: AlertTriangle,
    color: 'bg-red-100 dark:bg-red-900 text-red-600 dark:text-red-400',
    accent: 'border-red-300',
    title: 'Pago fallido',
    description: 'Se envía cuando no se pudo procesar el cobro de la renovación.',
    extraLabel: null,
  },
  {
    id: 'membership_expiring',
    icon: Clock3,
    color: 'bg-orange-100 dark:bg-orange-900 text-orange-600 dark:text-orange-400',
    accent: 'border-orange-300',
    title: 'Por vencer',
    description: 'Se envía si la membresía está por vencer y no tiene renovación automática.',
    extraLabel: 'Días antes del vencimiento',
  },
  {
    id: 'membership_expired',
    icon: XCircle,
    color: 'bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400',
    accent: 'border-gray-300',
    title: 'Vencida',
    description: 'Se envía cuando la membresía vence sin renovarse.',
    extraLabel: null,
  },
  {
    id: 'birthday',
    icon: Cake,
    color: 'bg-pink-100 dark:bg-pink-900 text-pink-600 dark:text-pink-400',
    accent: 'border-pink-300',
    title: 'Cumpleaños',
    description: 'Se envía el día del cumpleaños del miembro con una recompensa.',
    extraLabel: null,
  },
  {
    id: 'anniversary',
    icon: PartyPopper,
    color: 'bg-fuchsia-100 dark:bg-fuchsia-900 text-fuchsia-600 dark:text-fuchsia-400',
    accent: 'border-fuchsia-300',
    title: 'Aniversario',
    description: 'Se envía cada año en la fecha de alta, a partir del año indicado.',
    extraLabel: 'A partir del año',
  },
  {
    id: 'vip_milestone',
    icon: Trophy,
    color: 'bg-yellow-100 dark:bg-yellow-900 text-yellow-600 dark:text-yellow-400',
    accent: 'border-yellow-300',
    title: 'Hito VIP',
    description: 'Se envía cuando el miembro acumula renovaciones consecutivas sin cancelar.',
    extraLabel: 'Renovaciones consecutivas',
  },
  {
    id: 'visit_reminder',
    icon: CalendarClock,
    color: 'bg-cyan-100 dark:bg-cyan-900 text-cyan-600 dark:text-cyan-400',
    accent: 'border-cyan-300',
    title: 'Recordatorio de visita',
    description: 'Se envía si el miembro no visitó el local en los últimos días.',
    extraLabel: 'Días sin visitar',
  },
  {
    id: 'unused_benefits',
    icon: Gift,
    color: 'bg-teal-100 dark:bg-teal-900 text-teal-600 dark:text-teal-400',
    accent: 'border-teal-300',
    title: 'Beneficios sin usar',
    description: 'Se envía si el miembro no usó los servicios incluidos en su plan.',
    extraLabel: 'Días sin usar el beneficio',
  },
  {
    id: 'win_back',
    icon: RotateCcw,
    color: 'bg-indigo-100 dark:bg-indigo-900 text-indigo-600 dark:text-indigo-400',
    accent: 'border-indigo-300',
    title: 'Recuperación',
    description: 'Se envía a ex miembros para invitarlos a volver a sumarse.',
    extraLabel: 'Días desde la cancelación',
  },
]

const SEED_AUTOMATIONS = [
  {
    id: 'welcome',
    enabled: true,
    header: '¡Bienvenido/a al club! 👑',
    body: 'Gracias por unirte. Ya podés empezar a disfrutar los beneficios de tu plan.',
    extra_value: null,
  },
  {
    id: 'purchase_confirmed',
    enabled: true,
    header: 'Pago confirmado ✅',
    body: 'Tu suscripción está activa. Guardá tu tarjeta de membresía desde el link que te enviamos.',
    extra_value: null,
  },
  {
    id: 'renewal_reminder',
    enabled: true,
    header: 'Tu renovación se acerca 🔔',
    body: 'En unos días se renueva tu membresía. Si tenés dudas, escribinos.',
    extra_value: 3,
  },
  {
    id: 'renewal_successful',
    enabled: true,
    header: '¡Renovación exitosa! ✅',
    body: 'Seguís siendo parte del club. Gracias por tu confianza.',
    extra_value: null,
  },
  {
    id: 'payment_failed',
    enabled: true,
    header: 'No pudimos procesar tu pago ⚠️',
    body: 'Actualizá tu método de pago para no perder tus beneficios.',
    extra_value: null,
  },
  {
    id: 'membership_expiring',
    enabled: false,
    header: 'Tu membresía está por vencer ⏰',
    body: 'Renovala ahora para no perder tus beneficios exclusivos.',
    extra_value: 5,
  },
  {
    id: 'membership_expired',
    enabled: true,
    header: 'Tu membresía venció',
    body: 'Te extrañamos. Volvé a sumarte cuando quieras.',
    extra_value: null,
  },
  {
    id: 'birthday',
    enabled: true,
    header: '¡Feliz cumpleaños! 🎂',
    body: 'Como socio, tenés un regalo especial esperándote en tu próxima visita.',
    extra_value: null,
  },
  {
    id: 'anniversary',
    enabled: false,
    header: '¡Ya cumplimos un año juntos! 🎉',
    body: 'Gracias por seguir siendo parte del club. Tenemos un beneficio especial para vos.',
    extra_value: 1,
  },
  {
    id: 'vip_milestone',
    enabled: false,
    header: '¡Sos parte de nuestro top! 🏆',
    body: 'Por tu fidelidad, desbloqueaste un beneficio exclusivo.',
    extra_value: 6,
  },
  {
    id: 'visit_reminder',
    enabled: true,
    header: 'Hace rato no te vemos 👋',
    body: 'Tu membresía sigue activa. ¡Pasá cuando quieras!',
    extra_value: 14,
  },
  {
    id: 'unused_benefits',
    enabled: false,
    header: 'Tenés beneficios sin usar 🎁',
    body: 'Tu plan incluye servicios que todavía no aprovechaste este mes.',
    extra_value: 20,
  },
  {
    id: 'win_back',
    enabled: false,
    header: 'Te queremos de vuelta 💛',
    body: 'Volvé a sumarte al club y recuperá tus beneficios favoritos.',
    extra_value: 30,
  },
]

const SEED_MEMBERSHIP_DATA = {
  settings: {
    business_name: 'Barber Club Pro',
    subtitle: 'Membresías premium',
    color: '#111827',
    logo_url: '',
    slug: 'barber-club-pro',
  },
  plans: SEED_PLANS,
  members: SEED_MEMBERS,
  automations: SEED_AUTOMATIONS,
}

// ─── Persistencia ──────────────────────────────────────────────────────────────

export function loadMembershipData() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (stored) {
      const data = JSON.parse(stored)
      // Migración: datos guardados antes de que existiera `automations` no lo tienen.
      if (!data.automations) data.automations = JSON.parse(JSON.stringify(SEED_AUTOMATIONS))
      // Migración: `billing_period` (monthly/annual) → `billing_period_days` (número).
      data.plans?.forEach((plan) => {
        if (plan.billing_period_days == null) {
          plan.billing_period_days = plan.billing_period === 'annual' ? 365 : 30
        }
      })
      return data
    }
  } catch {
    /* ignore */
  }
  return JSON.parse(JSON.stringify(SEED_MEMBERSHIP_DATA))
}

export function saveMembershipData(data) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data))
  } catch {
    /* ignore */
  }
}

export function resetMembershipData() {
  const fresh = JSON.parse(JSON.stringify(SEED_MEMBERSHIP_DATA))
  saveMembershipData(fresh)
  return fresh
}
