// Catálogo de ejemplo del menú digital de Café Moon. Se usa como dato de muestra
// en el builder de admin (Menu.jsx) cuando no hay nada guardado en localStorage
// todavía, y como fallback en la vista pública (PublicMenu.jsx) para que el menú
// nunca se vea vacío — p. ej. si alguien escanea un QR compartido en un
// dispositivo nuevo, antes de que el negocio configure su propio catálogo.
export const SAMPLE_CATALOG = {
  categories: ['Bebidas', 'Comidas', 'Postres'],
  settings: {
    name: 'Moon Café',
    subtitle: 'Gracias por elegirnos',
    color: '#111827',
    logo_url: '',
    logo_type: 'square',
    banner_url: '',
  },
  items: [
    {
      id: 'demo_1',
      name: 'Café con leche',
      description: 'Espresso doble con leche vaporizada. Perfecto para comenzar el día.',
      image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=75',
      price_type: 'money',
      price: 850,
      category: 'Bebidas',
      stock_enabled: false,
      stock: null,
      available: true,
    },
    {
      id: 'demo_2',
      name: 'Cappuccino',
      description: 'Espresso con leche vaporizada y espuma cremosa. Clásico italiano.',
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=75',
      price_type: 'money',
      price: 950,
      category: 'Bebidas',
      stock_enabled: false,
      stock: null,
      available: true,
    },
    {
      id: 'demo_3',
      name: 'Jugo de naranja',
      description: 'Jugo natural exprimido al momento.',
      image_url: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&q=75',
      price_type: 'money',
      price: 700,
      category: 'Bebidas',
      stock_enabled: false,
      stock: null,
      available: true,
    },
    {
      id: 'demo_4',
      name: 'Medialunas x3',
      description: 'Tres medialunas de manteca, tiernas y doradas.',
      image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=75',
      price_type: 'points',
      price: 50,
      category: 'Comidas',
      stock_enabled: false,
      stock: null,
      available: true,
    },
    {
      id: 'demo_5',
      name: 'Tostado jamón y queso',
      description: 'Pan artesanal tostado con jamón natural y queso cremoso.',
      image_url: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=600&q=75',
      price_type: 'money',
      price: 1200,
      category: 'Comidas',
      stock_enabled: false,
      stock: null,
      available: true,
    },
    {
      id: 'demo_6',
      name: 'Bowl de granola',
      description: 'Granola artesanal con yogur, frutas de temporada y miel.',
      image_url: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=75',
      price_type: 'points',
      price: 80,
      category: 'Comidas',
      stock_enabled: false,
      stock: null,
      available: true,
    },
    {
      id: 'demo_7',
      name: 'Brownie de chocolate',
      description: 'Brownie húmedo con chips de chocolate negro. Irresistible.',
      image_url: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=600&q=75',
      price_type: 'points',
      price: 60,
      category: 'Postres',
      stock_enabled: true,
      stock: 8,
      available: true,
    },
    {
      id: 'demo_8',
      name: 'Cheesecake de frutos rojos',
      description: 'Cheesecake cremoso con coulis de frutos rojos. Porción individual.',
      image_url: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=75',
      price_type: 'money',
      price: 1100,
      category: 'Postres',
      stock_enabled: false,
      stock: null,
      available: true,
    },
  ],
}
