export const STAMPS_TYPE_ID = '7aedc7a8-b1c9-4fa3-a0b0-4ea74b6fc151'
export const POINTS_TYPE_ID = '7aedc7a8-b1c9-4fa3-a0b0-4ea74b6fc157'
export const MEMBERSHIP_TYPE_ID = '7aedc7a8-b1c9-4fa3-a0b0-4ea74b6fc155'

// ProgramPreviewComponent treats any URL not starting with http(s)/data: as a backend-relative
// path and prefixes it with the API origin. These are static frontend assets, so we need
// absolute same-origin URLs instead.
const asset = (path) => `${window.location.origin}${path}`

const BASE_CLUB = {
  reward_tiers: [],
  stamp_image_url: asset('/mooncafe-stamp.jpg'),
  stamp_icon_bg_color: '#1a4a2e',
  card_color: '#1a4a2e',
  foreground_color: '#ffffff',
  label_color: '#ffffff',
  contact_email: '',
  contact_phone: '',
  website: 'cafemoon.com.ar',
  security_ticket_required: false,
  security_geofence_required: false,
  security_cooldown_hours: 0,
  validity_stamps_days: 0,
  validity_reward_days: 0,
  validity_duration_days: 0,
  collect_name: true,
  collect_email: true,
  collect_phone: false,
  collect_birthday: false,
  selected_store_ids: ['store-1'],
  coupon_trigger: 'purchase',
  coupon_benefit_type: 'percent',
  coupon_benefit_value: 10,
  coupon_description: '',
  coupon_validity_days: 30,
  membership_activation: 'free',
  membership_tiers: [],
  membership_catalog: [],
  membership_partners: [],
  ticker_items: [],
  novedades: [],
  referral_reward_cashback: 500,
  referral_reward_membership_type: 'days',
  referral_reward_membership_days: 30,
  referral_reward_membership_benefit: '',
  cashback_percentage: 5,
  cashback_min_purchase: 0,
  cashback_min_redeem: 500,
  cashback_validity_days: 365,
}

export const MOONCAFE_STORES = [
  {
    store_id: 'store-1',
    store_name: 'Café Moon · Sucursal Centro',
    address: 'Av. Corrientes 1234',
    city: 'Buenos Aires',
  },
]

export const MOONCAFE_BRAND = { brand_name: 'Café Moon', logo_url: asset('/moon-cafe-logo.png') }

export const MOONCAFE_CLUBS = [
  {
    ...BASE_CLUB,
    id: 'mooncafe-sellos',
    club_name: 'Club Moon Cafe',
    card_title: 'Programa de Sellos',
    short_url: asset('/publicprogram-demo/mooncafe'),
    program_type_id: STAMPS_TYPE_ID,
    description: 'Programa de sellos de Café Moon',
    reward_text: 'Cada 5 cafés, 1 GRATIS ☕',
    stamps_required: 5,
    logo_url: asset('/moon-cafe-logo.png'),
    background_image_url: asset('/mooncafe-bg.jpg'),
    terms: `Club Moon Cafe es el programa de fidelidad de Café Moon. Al registrarse, el usuario acepta los siguientes términos:\n\n• Por cada café comprado se acumula 1 sello.\n• Al completar 5 sellos se obtiene 1 café gratis.\n• Los sellos no son transferibles ni canjeables por dinero.\n• Café Moon se reserva el derecho de modificar los beneficios con previo aviso.\n• La membresía es personal e intransferible.`,
    is_active: true,
    members: 148,
    total_scans: 294,
    rewards_redeemed: 24,
  },
  {
    ...BASE_CLUB,
    id: 'mooncafe-membresia',
    club_name: 'Moon Club',
    card_title: 'Membresía Moon',
    short_url: asset('/publicprogram-demo/mooncafe'),
    program_type_id: MEMBERSHIP_TYPE_ID,
    description: 'Accedé a beneficios exclusivos y descuentos en comercios aliados de Moon Café.',
    reward_text: '',
    stamps_required: 0,
    logo_url: asset('/moon-cafe-logo.png'),
    background_image_url: asset('/mooncafe-bg.jpg'),
    card_color: '#2d1b69',
    foreground_color: '#ffffff',
    label_color: '#c4b5fd',
    terms: `Moon Club es el programa de membresía de Café Moon. Al unirte aceptás los siguientes términos:\n\n• La membresía es personal e intransferible.\n• Los beneficios están sujetos a disponibilidad de cada comercio adherido.\n• Café Moon puede modificar o reemplazar beneficios con 15 días de aviso.\n• Los descuentos en comercios aliados no son acumulables con otras promociones.`,
    is_active: true,
    members: 148,
    total_scans: 0,
    rewards_redeemed: 0,
    membership_activation: 'tiers',
    membership_tiers: [
      { id: 'tier-basico', name: 'Básico', min_spend: 0, color: '#6b7280' },
      {
        id: 'tier-premium',
        name: 'Premium',
        min_spend: 5000,
        color: '#f59e0b',
        sub_price: 1500,
        sub_period: 'monthly',
      },
    ],
    membership_catalog: [
      {
        id: 1001,
        name: 'Café gratis en tu cumpleaños',
        description: 'Un café de tu elección sin costo el día de tu cumple.',
        use_type: 'onetime',
        tier_required: 'all',
        image_url: null,
      },
      {
        id: 1002,
        name: '2x1 en bebidas calientes los miércoles',
        description: 'Pedís uno y te llevás dos. Válido solo los miércoles.',
        use_type: 'monthly',
        tier_required: 'all',
        image_url: null,
      },
      {
        id: 1003,
        name: '10% de descuento en todo el menú',
        description: 'Descuento automático en cada visita.',
        use_type: 'unlimited',
        tier_required: 'tier-premium',
        image_url: null,
      },
      {
        id: 1004,
        name: 'Mesa reservada sin espera',
        description: 'Reservá tu lugar con prioridad en cualquier sucursal.',
        use_type: 'unlimited',
        tier_required: 'tier-premium',
        image_url: null,
      },
    ],
    membership_partners: [
      {
        id: 2001,
        partner_name: 'La Madeleine',
        benefit_name: '15% en pastelería artesanal',
        description: 'Presentá tu tarjeta Moon Club en el local.',
        category: 'gastronomia',
        use_type: 'unlimited',
        tier_required: 'all',
        logo_url: null,
      },
      {
        id: 2002,
        partner_name: 'Pilates Studio BA',
        benefit_name: 'Clase de prueba gratuita',
        description: 'Primera clase sin cargo para nuevos miembros.',
        category: 'salud',
        use_type: 'onetime',
        tier_required: 'all',
        logo_url: null,
      },
      {
        id: 2003,
        partner_name: 'Libros & Idea',
        benefit_name: '10% en libros seleccionados',
        description: 'Descuento en toda la colección de novedades.',
        category: 'entretenimiento',
        use_type: 'unlimited',
        tier_required: 'all',
        logo_url: null,
      },
      {
        id: 2004,
        partner_name: 'Barbería Urban',
        benefit_name: 'Corte + barba a $2.500 (valor normal $3.800)',
        description: 'Con turno previo. Sujeto a disponibilidad.',
        category: 'servicios',
        use_type: 'monthly',
        tier_required: 'tier-premium',
        logo_url: null,
      },
    ],
    ticker_items: [
      '☕ Cappuccino artesanal',
      '🥐 Medialunas de manteca',
      '🍵 Matcha latte',
      '❄️ Cold brew',
      '🎉 Eventos para socios',
      '✨ Nuevos fríos de temporada',
    ],
    novedades: [
      {
        id: 1,
        type: 'novedad',
        title: 'Nueva línea de fríos de temporada',
        body: 'Tereré de limón, cold brew con naranja y limonada de jengibre. Solo por julio.',
        image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=400&fit=crop&q=80',
        date: '7 jul',
      },
      {
        id: 2,
        type: 'promo',
        title: 'Julio: 2x1 todos los miércoles',
        body: 'Aprovechá el beneficio de tu membresía. Válido en todas las bebidas calientes.',
        image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop&q=80',
        date: '1 jul',
      },
      {
        id: 3,
        type: 'evento',
        title: 'Cata de cafés de origen — sáb 19',
        body: 'Junto a nuestros baristas, exploramos 4 orígenes distintos. Cupos limitados.',
        image_url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&h=400&fit=crop&q=80',
        date: '25 jun',
      },
      {
        id: 4,
        type: 'novedad',
        title: 'Abrimos en Palermo — Thames 1540',
        body: 'Nuestra segunda sucursal ya está abierta. Seguís acumulando beneficios en cualquiera.',
        image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop&q=80',
        date: '18 jun',
      },
    ],
  },
  {
    ...BASE_CLUB,
    id: 'mooncafe-puntos',
    club_name: 'Club Moon Cafe',
    card_title: 'Programa de Puntos',
    short_url: asset('/publicprogram-demo/mooncafe-points'),
    program_type_id: POINTS_TYPE_ID,
    description: 'Programa de puntos de Café Moon',
    reward_text: '100 puntos = desayuno gratis 💚',
    stamps_required: 20,
    money_per_point: 1000,
    money_per_point_redeem: 100,
    redeem_mode: 'direct',
    logo_url: asset('/moon-cafe-logo.png'),
    background_image_url: asset('/mooncafe-bg.jpg'),
    terms: `Club Moon Cafe es el programa de fidelidad de Café Moon. Al registrarse, el usuario acepta los siguientes términos:\n\n• Por cada compra se acumulan puntos según el monto gastado.\n• Al llegar a 100 puntos se obtiene un desayuno gratis.\n• Los puntos no son transferibles ni canjeables por dinero.\n• Café Moon se reserva el derecho de modificar los beneficios con previo aviso.\n• La membresía es personal e intransferible.`,
    is_active: true,
    members: 148,
    total_scans: 2940,
    rewards_redeemed: 24,
  },
]

export const getValidityTermsText = (days) =>
  days > 0 ? `Plazo para juntar sellos: ${days} días, de lo contrario tu tarjeta vuelve a 0.` : ''
