import { createContext, useContext, useState, useEffect } from 'react'
import { getCurrentUser } from '@/utils/jwt'

const LanguageContext = createContext()

export const translations = {
  es: {
    dashboard: 'Dashboard',
    myPrograms: 'Mis Clubes',
    customers: 'Miembros',
    stores: 'Sucursales',
    notifications: 'Notificaciones',
    comingSoon: 'Próximamente',
    team: 'Equipo',
    manageTeamDesc: 'Administra roles de usuario y acceso a sucursales',
    createProgram: 'Crear Club',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    search: 'Buscar...',
    welcome: 'Bienvenido',
    settings: 'Configuración',
    save: 'Guardar',
    cancel: 'Cancelar',
    actions: 'Acciones',
    role: 'Rol',
    admin: 'Administrador',
    employee: 'Empleado',
    store: 'Sucursal',
    allStores: 'Sucursales',
    password: 'Contraseña',
    changePassword: 'Cambiar Contraseña',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    dashboardSubtitle: 'Revisa las estadisticas de tu negocio',
    filterStore: 'Filtrar por Sucursal',
    filterPeriod: 'Seleccionar periodo',
    periodDefault: 'Predeterminado',
    period7d: 'Últimos 7 días',
    periodMonth: 'Este Mes',
    periodCustom: 'Personalizado',
    allTime: 'Todo el tiempo',
    pickDate: 'Elegir fecha',
    programMembers: 'Miembros del Club',
    activePrograms: 'Clubes Activos',
    stamps: 'Sellos',
    rewards: 'Premios',
    redemptionRate: 'Tasa de Canje',
    thisWeek: 'esta semana',
    membersChartTitle7d: 'Miembros (Últimos 7 días)',
    membersChartTitleMonth: 'Miembros (Este mes)',
    membersChartTitle: 'Miembros',
    myProgramsSubtitle: 'Maneja tus clubes de fidelidad',
    searchPrograms: 'buscar clubes...',
    noProgramsTitle: 'No hay Clubes aún',
    noProgramsDesc: 'Comienza creando tu primer club de fidelidad',
    noProgramsForStore: 'No hay clubes en esta sucursal',
    noProgramsForStoreDesc: 'No se encontraron clubes asociados a la sucursal seleccionada',
    createFirstProgram: 'Crea tu primer Club',
    customersSubtitle: 'Usuarios que agregaron tus tarjetas',
    searchEmail: 'Buscar por email...',
    filterMonth: 'Filtrar por mes',
    filterProgram: 'Filtrar por Club',
    filterStamps: 'Filtrar por sellos',
    allMonths: 'Meses',
    allPrograms: 'Clubes',
    allStamps: 'Todos',
    showingCustomers: 'Mostrando',
    customersCount: 'miembros',
    noCustomersTitle: 'No se encontraron miembros',
    noCustomersDesc: 'Cuando los usuarios agreguen tus clubes, aparecerán aquí',
    unknownProgram: 'Club Desconocido',
    noEmail: 'Sin correo',
    stamp: 'Sello',
    manageAccount: 'Administra tu cuenta y suscripción',
    programsCreated: 'Clubes Creados',
    assignedStore: 'Sucursal Asignada',
    unassigned: 'Sin asignar',
    subscription: 'Suscripción',
    active: 'Activa',
    freePlan: 'Plan Gratuito',
    planFeature1: 'Hasta 5 clubes de lealtad',
    planFeature2: 'Analíticas básicas',
    planFeature3: 'Soporte estándar',
    upgradePlan: 'Mejorar Plan',
    stampsDistributionTitle: 'Distribución de Sellos',
    stampsDistributionSubtitle: 'Miembros agrupados por cantidad de sellos',
    stampSingular: 'sello',
    stampPlural: 'sellos',
    stampsChartTitle: 'Sellos Entregados',
    rewardsChartTitle: 'Premios Entregados',
    backToPrograms: 'Volver a Tus Clubes',
    editProgram: 'Editar Club',
    createNewProgram: 'Crear Nuevo Club',
    livePreview: 'Vista Previa',
    livePreviewDesc: 'Asi es cómo se verá tu tarjeta',
    clubName: 'Nombre del Club',
    clubNamePlaceholder: 'Ej. Club de Puntos',
    programTitle: 'Título de la Tarjeta',
    programTitlePlaceholder: 'Ej. Recompensas',
    description: 'Descripción',
    descriptionPlaceholder: 'Describe tu Club de fidelidad...',
    rewardOffer: 'Oferta de Recompensa',
    rewardOfferPlaceholder: 'Ej. Compra 10, lleva 1 gratis',
    stampsRequired: 'Sellos Requeridos',
    logo: 'Logotipo',
    uploadLogo: 'Subir Logo',
    primaryColor: 'Color de la Tarjeta',
    gradientColor: 'Color Secundario',
    contactEmail: 'Email de Contacto',
    contactPhone: 'Teléfono de Contacto',
    website: 'Sitio Web',
    termsAndConditions: 'Términos y Condiciones',
    termsPlaceholder: 'Ingresa los términos y condiciones...',
    updateClub: 'Actualizar Club',
    createProgramBtn: 'Crear Club',
    securityAndFraud: 'Seguridad y Fraude',
    validityAndTerms: 'Plazos y Vigencias',
    requireTicket: 'Requerir Ticket de Compra',
    requireTicketDesc: 'Solicitar número de ticket y monto al dar sellos',
    locationValidation: 'Validación de Ubicación',
    locationValidationDesc: 'Solo permitir dar sellos dentro de la sucursal',
    cooldownTime: 'Tiempo de espera entre sellos (horas)',
    cooldownTimeDesc: 'Evita que un mismo cliente reciba múltiples sellos en poco tiempo',
    noTimeLimit: '0 = Sin límite',
    stampsValidity: 'Plazo para juntar sellos',
    rewardValidity: 'Plazo para canjear premio',
    programValidity: 'Vigencia del Club',
    alwaysActive: '0 = Siempre activa',
    days: 'Días',
    selectLocation: 'Selecciona Ubicación',
    whereWorking: '¿Dónde estás trabajando hoy?',
    chooseStore: 'Elige una sucursal...',
    scanCustomerQR: 'Escanear código QR del cliente',
    positionQR: 'Posiciona el código QR dentro del marco',
    change: 'Cambiar',
    cameraNotAvailable: 'Cámara no disponible',
    allowCameraAccess: 'Por favor permite el acceso a la cámara',
    goBack: 'Volver',
    survey: 'Encuesta',
    menu: 'Menú',
    notificationsDescription: 'Envía notificaciones push a los usuarios que agregaron tus tarjetas a su wallet',
    notificationProgram: 'Club',
    notificationAllPrograms: 'Todos los clubes',
    notificationHeader: 'Título',
    notificationHeaderPlaceholder: 'Ej. ¡Oferta especial!',
    notificationBody: 'Mensaje',
    notificationBodyPlaceholder: 'Ej. Visítanos hoy y obtén el doble de sellos',
    notificationSend: 'Enviar notificación',
    notificationSent: 'Notificación enviada exitosamente',
    notificationError: 'Error al enviar la notificación',
    notificationInfo:
      'La notificación se enviará a todos los usuarios con tarjetas en Google Wallet. Los usuarios con Apple Wallet recibirán una actualización silenciosa.',
  },
  en: {
    dashboard: 'Dashboard',
    myPrograms: 'My Programs',
    customers: 'Members',
    stores: 'Stores',
    notifications: 'Notifications',
    comingSoon: 'Coming Soon',
    team: 'Team',
    manageTeamDesc: 'Manage user roles and store access',
    createProgram: 'Create Program',
    profile: 'Profile',
    logout: 'Log Out',
    search: 'Search...',
    welcome: 'Welcome',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    actions: 'Actions',
    role: 'Role',
    admin: 'Admin',
    employee: 'Employee',
    store: 'Store',
    allStores: 'All Stores',
    password: 'Password',
    changePassword: 'Change Password',
    language: 'Language',
    selectLanguage: 'Select Language',
    dashboardSubtitle: 'Check your loyalty program statistics',
    filterStore: 'Filter by Store',
    filterPeriod: 'Select period',
    periodDefault: 'Default',
    period7d: 'Last 7 days',
    periodMonth: 'This Month',
    periodCustom: 'Custom',
    allTime: 'All time',
    pickDate: 'Pick a date',
    programMembers: 'Program Members',
    activePrograms: 'Active Programs',
    stamps: 'Stamps',
    rewards: 'Rewards',
    redemptionRate: 'Redemption Rate',
    thisWeek: 'this week',
    membersChartTitle7d: 'Members (Last 7 days)',
    membersChartTitleMonth: 'Members (This Month)',
    membersChartTitle: 'Members',
    myProgramsSubtitle: 'Manage your Loyalty Programs',
    searchPrograms: 'search programs...',
    noProgramsTitle: 'No programs yet',
    noProgramsDesc: 'Start by creating your first loyalty program',
    noProgramsForStore: 'No programs in this store',
    noProgramsForStoreDesc: 'No programs were found associated with the selected store',
    createFirstProgram: 'Create your first program',
    customersSubtitle: 'Users who added your loyalty programs to their wallet',
    searchEmail: 'Search by email...',
    filterMonth: 'Filter by month',
    filterProgram: 'Filter by program',
    filterStamps: 'Filter by stamps',
    allMonths: 'All Months',
    allPrograms: 'All Programs',
    allStamps: 'All',
    showingCustomers: 'Showing',
    customersCount: 'members',
    noCustomersTitle: 'No members found',
    noCustomersDesc: "When users add your programs to their wallet, they'll appear here",
    unknownProgram: 'Unknown Program',
    noEmail: 'No email',
    stamp: 'Stamp',
    manageAccount: 'Manage your account and subscription',
    programsCreated: 'Programs Created',
    assignedStore: 'Assigned Store',
    unassigned: 'Unassigned',
    subscription: 'Subscription',
    active: 'Active',
    freePlan: 'Free Plan',
    planFeature1: 'Up to 5 loyalty programs',
    planFeature2: 'Basic analytics',
    planFeature3: 'Standard support',
    upgradePlan: 'Upgrade Plan',
    stampsDistributionTitle: 'Stamps Distribution',
    stampsDistributionSubtitle: 'Members grouped by stamp count',
    stampSingular: 'stamp',
    stampPlural: 'stamps',
    stampsChartTitle: 'Stamps Given',
    rewardsChartTitle: 'Rewards Given',
    backToPrograms: 'Back to Programs',
    editProgram: 'Edit Program',
    createNewProgram: 'Create New Program',
    livePreview: 'Live Preview',
    livePreviewDesc: 'See how your program will look',
    clubName: 'Club Name',
    clubNamePlaceholder: 'e.g., Points Club',
    programTitle: 'Program Title',
    programTitlePlaceholder: 'e.g., Loyalty Rewards',
    description: 'Description',
    descriptionPlaceholder: 'Describe your loyalty program...',
    rewardOffer: 'Reward Offer',
    rewardOfferPlaceholder: 'e.g., Buy 10, Get 1 Free',
    stampsRequired: 'Stamps Required',
    logo: 'Logo',
    uploadLogo: 'Upload Logo',
    primaryColor: 'Primary Color',
    gradientColor: 'Gradient Color',
    contactEmail: 'Contact Email',
    contactPhone: 'Contact Phone',
    website: 'Website',
    termsAndConditions: 'Terms & Conditions',
    termsPlaceholder: 'Enter terms and conditions...',
    updateProgram: 'Update Program',
    createProgramBtn: 'Create Program',
    securityAndFraud: 'Security & Fraud',
    validityAndTerms: 'Validity & Terms',
    requireTicket: 'Require Purchase Ticket',
    requireTicketDesc: 'Request ticket number and amount when giving stamps',
    locationValidation: 'Location Validation',
    locationValidationDesc: 'Only allow giving stamps within the store',
    cooldownTime: 'Cooldown between stamps (hours)',
    cooldownTimeDesc: 'Prevent same customer from getting multiple stamps in short time',
    noTimeLimit: '0 = No limit',
    stampsValidity: 'Time to collect stamps',
    rewardValidity: 'Time to redeem reward',
    programValidity: 'Program validity',
    alwaysActive: '0 = Always active',
    days: 'Days',
    selectLocation: 'Select Location',
    whereWorking: 'Where are you working today?',
    chooseStore: 'Choose a store...',
    scanCustomerQR: "Scan customer's QR code",
    positionQR: 'Position the QR code within the frame',
    change: 'Change',
    cameraNotAvailable: 'Camera not available',
    allowCameraAccess: 'Please allow camera access to scan QR codes',
    goBack: 'Go Back',
    survey: 'Survey',
    menu: 'Menu',
    notificationsDescription: 'Send push notifications to users who added your cards to their wallet',
    notificationProgram: 'Program',
    notificationAllPrograms: 'All programs',
    notificationHeader: 'Header',
    notificationHeaderPlaceholder: 'e.g., Special offer!',
    notificationBody: 'Message',
    notificationBodyPlaceholder: 'e.g., Visit us today and get double stamps',
    notificationSend: 'Send notification',
    notificationSent: 'Notification sent successfully',
    notificationError: 'Error sending notification',
    notificationInfo:
      'The notification will be sent to all users with cards in Google Wallet. Apple Wallet users will receive a silent update.',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('es')
  const [isLoaded, setIsLoaded] = useState(false)

  useEffect(() => {
    // Load initial language from user profile if available, or local storage
    const loadLanguage = () => {
      try {
        const user = getCurrentUser()
        if (user?.language) {
          setLanguage(user.language)
        } else {
          const saved = localStorage.getItem('app_language')
          if (saved) setLanguage(saved)
        }
      } catch {
        // User not logged in or error
        const saved = localStorage.getItem('app_language')
        if (saved) setLanguage(saved)
      } finally {
        setIsLoaded(true)
      }
    }
    loadLanguage()
  }, [])

  const changeLanguage = async (lang) => {
    setLanguage(lang)
    localStorage.setItem('app_language', lang)
    // Nota: api.auth.updateMe() no existe en el backend según el YAML
    // El idioma se guarda solo en localStorage hasta que el backend implemente PATCH /auth/me
    // try {
    //    await api.auth.updateMe({ language: lang });
    // } catch (e) {
    //   console.error("Failed to save language preference", e);
    // }
  }

  const t = (key) => translations[language][key] || key

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, isLoaded }}>{children}</LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
