import { createContext, useContext, useState, useEffect } from 'react'
import { getCurrentUser } from '@/utils/jwt'

const LanguageContext = createContext()

export const translations = {
  es: {
    // Navigation & Layout
    dashboard: 'Dashboard',
    myPrograms: 'Mis Clubes',
    customers: 'Miembros',
    stores: 'Sucursales',
    notifications: 'Notificaciones',
    comingSoon: 'Próximamente',
    team: 'Equipo',
    createProgram: 'Crear Club',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    survey: 'Encuesta',
    menu: 'Menú',

    // Common / Shared
    search: 'Buscar...',
    welcome: 'Bienvenido',
    settings: 'Configuración',
    save: 'Guardar',
    cancel: 'Cancelar',
    actions: 'Acciones',
    goBack: 'Volver',
    change: 'Cambiar',
    days: 'Días',
    active: 'Activa',
    showing: 'Mostrando',
    of: 'de',
    sortBy: 'Ordenar por',
    sortByDate: 'Fecha registro',
    sortByVisits: 'Visitas totales',

    // Sidebar
    support: 'Soporte',
    logoutSuccess: 'Sesión cerrada exitosamente',
    logoutError: 'Error al cerrar sesión',

    // Dashboard
    dashboardSubtitle: 'Revisa las estadisticas de tu negocio',
    dashboardLoadError: 'Error cargando el dashboard',
    programMembers: 'Miembros del Club',
    activePrograms: 'Clubes Activos',
    stamps: 'Sellos',
    rewards: 'Premios',
    redemptionRate: 'Tasa de Canje',
    thisWeek: 'esta semana',
    membersChartTitle7d: 'Miembros (Últimos 7 días)',
    membersChartTitleMonth: 'Miembros (Este mes)',
    membersChartTitle: 'Miembros',
    stampsChartTitle: 'Sellos Entregados',
    rewardsChartTitle: 'Premios Entregados',
    stampsDistributionTitle: 'Distribución de Sellos',
    stampsDistributionSubtitle: 'Miembros agrupados por cantidad de sellos',
    stampSingular: 'sello',
    stampPlural: 'sellos',

    // Filters (shared across pages)
    filterStore: 'Filtrar por Sucursal',
    filterPeriod: 'Seleccionar periodo',
    periodDefault: 'Predeterminado',
    period7d: 'Últimos 7 días',
    periodMonth: 'Este Mes',
    periodCustom: 'Personalizado',
    allTime: 'Todo el tiempo',
    pickDate: 'Elegir fecha',
    filterMonth: 'Filtrar por mes',
    filterProgram: 'Filtrar por Club',
    filterStamps: 'Filtrar por sellos',
    allMonths: 'Meses',
    allPrograms: 'Clubes',
    allStamps: 'Todos',

    // Stores
    store: 'Sucursal',
    allStores: 'Sucursales',
    storesTitle: 'Sucursales',
    storesSubtitle: 'Gestiona las ubicaciones de tu negocio',
    accessDenied: 'Acceso denegado. Solo administradores.',
    selectLocation: 'Selecciona Ubicación',
    whereWorking: '¿Dónde estás trabajando hoy?',
    chooseStore: 'Elige una sucursal...',

    // MyPrograms
    myProgramsSubtitle: 'Maneja tus clubes de fidelidad',
    searchPrograms: 'buscar clubes...',
    noProgramsTitle: 'No hay Clubes aún',
    noProgramsDesc: 'Comienza creando tu primer club de fidelidad',
    noProgramsForStore: 'No hay clubes en esta sucursal',
    noProgramsForStoreDesc: 'No se encontraron clubes asociados a la sucursal seleccionada',
    createFirstProgram: 'Crea tu primer Club',

    // Customers
    customersSubtitle: 'Usuarios que agregaron tus tarjetas',
    searchEmail: 'Buscar por email...',
    showingCustomers: 'Mostrando',
    customersCount: 'miembros',
    noCustomersTitle: 'No se encontraron miembros',
    noCustomersDesc: 'Cuando los usuarios agreguen tus clubes, aparecerán aquí',
    unknownProgram: 'Club Desconocido',
    noEmail: 'Sin correo',
    stamp: 'Sello',

    // CreateClub form
    backToPrograms: 'Volver a Tus Clubes',
    editProgram: 'Editar Club',
    createNewProgram: 'Crear Nuevo Club',
    livePreview: 'Vista Previa',
    livePreviewDesc: 'Asi es cómo se verá tu tarjeta',
    clubName: 'Nombre del Club',
    clubNamePlaceholder: 'Ej. Club de Puntos',
    programTitle: 'Título de la Tarjeta',
    programTitlePlaceholder: 'Ej. Recompensas',
    description: 'Descripción',
    descriptionPlaceholder: 'Describe tu Club de fidelidad...',
    rewardOffer: 'Oferta de Recompensa',
    rewardOfferPlaceholder: 'Ej. Compra 10, lleva 1 gratis',
    stampsRequired: 'Sellos Requeridos',
    logo: 'Logotipo',
    uploadLogo: 'Subir Logo',
    primaryColor: 'Color de la Tarjeta',
    gradientColor: 'Color Secundario',
    contactEmail: 'Email de Contacto',
    contactPhone: 'Teléfono de Contacto',
    website: 'Sitio Web',
    termsAndConditions: 'Términos y Condiciones',
    termsPlaceholder: 'Ingresa los términos y condiciones...',
    updateClub: 'Actualizar Club',
    createProgramBtn: 'Crear Club',
    securityAndFraud: 'Seguridad y Fraude',
    validityAndTerms: 'Plazos y Vigencias',
    requireTicket: 'Requerir Ticket de Compra',
    requireTicketDesc: 'Solicitar número de ticket y monto al dar sellos',
    locationValidation: 'Validación de Ubicación',
    locationValidationDesc: 'Solo permitir dar sellos dentro de la sucursal',
    cooldownTime: 'Tiempo de espera entre sellos (horas)',
    cooldownTimeDesc: 'Evita que un mismo cliente reciba múltiples sellos en poco tiempo',
    noTimeLimit: '0 = Sin límite',
    stampsValidity: 'Plazo para juntar sellos',
    rewardValidity: 'Plazo para canjear premio',
    programValidity: 'Vigencia del Club',
    alwaysActive: '0 = Siempre activa',

    // Profile
    manageAccount: 'Administra tu cuenta y suscripción',
    programsCreated: 'Clubes Creados',
    assignedStore: 'Sucursal Asignada',
    unassigned: 'Sin asignar',
    password: 'Contraseña',
    changePassword: 'Cambiar Contraseña',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    role: 'Rol',
    admin: 'Administrador',
    employee: 'Empleado',

    // Subscription
    subscription: 'Suscripción',
    freePlan: 'Plan Gratuito',
    planFeature1: 'Hasta 5 clubes de lealtad',
    planFeature2: 'Analíticas básicas',
    planFeature3: 'Soporte estándar',
    upgradePlan: 'Mejorar Plan',

    // Team
    manageTeamDesc: 'Administra roles de usuario y acceso a sucursales',

    // Notifications
    notificationsDescription: 'Envía notificaciones push a los usuarios que agregaron tus tarjetas a su wallet',
    notificationProgram: 'Club',
    notificationAllPrograms: 'Todos los clubes',
    notificationHeader: 'Título',
    notificationHeaderPlaceholder: 'Ej. ¡Oferta especial!',
    notificationBody: 'Mensaje',
    notificationBodyPlaceholder: 'Ej. Visítanos hoy y obtén el doble de sellos',
    notificationSend: 'Enviar notificación',
    notificationSent: 'Notificación enviada exitosamente',
    notificationError: 'Error al enviar la notificación',
    notificationInfo:
      'La notificación se enviará a todos los usuarios con tarjetas en Google Wallet. Los usuarios con Apple Wallet recibirán una actualización silenciosa.',

    // Login & Auth
    loginTitle: 'Iniciar sesión',
    loginCreateAccount: 'Crear cuenta',
    loginWelcomeBack: 'Bienvenido de vuelta',
    loginStartJourney: 'Comienza tu viaje con nosotros',
    loginContinueWithEmail: 'Continúa con tu email',
    loginName: 'Nombre',
    loginNamePlaceholder: 'Tu nombre completo',
    loginForgotPassword: '¿Olvidaste tu contraseña?',
    loginMinChars: 'Mínimo 8 caracteres',
    loginUppercase: 'Al menos una letra mayúscula',
    loginNumber: 'Al menos un número',
    loginSigningIn: 'Iniciando sesión...',
    loginCreatingAccount: 'Creando cuenta...',
    loginNoAccount: '¿No tienes cuenta? ',
    loginHaveAccount: '¿Ya tienes cuenta? ',
    loginRegister: 'Regístrate',
    loginSuccessToast: '¡Inicio de sesión exitoso!',
    loginAuthError: 'Error al procesar la autenticación. Intenta nuevamente.',
    loginInvalidCredentials: 'Credenciales inválidas. Intenta nuevamente.',
    loginNetworkError: 'Error de conexión. Verifica tu conexión a internet e intenta nuevamente.',
    loginVerifyEmail: 'Por favor verifica tu correo electrónico antes de iniciar sesión',
    loginRegisterSuccess: '¡Registro exitoso! Por favor verifica tu correo electrónico.',
    loginRegisterError: 'Error al registrarse',
    loginError: 'Error al iniciar sesión',
    loginShowPassword: 'Mostrar contraseña',
    loginHidePassword: 'Ocultar contraseña',
    loginVerificationSent: 'Se ha enviado un correo de verificación a',
    loginVerificationCheck:
      'Por favor revisa tu bandeja de entrada (y la carpeta de spam) y haz clic en el enlace para activar tu cuenta.',
    loginVerificationSpam:
      'Si no recibes el correo en unos minutos, verifica tu carpeta de spam o contacta al administrador.',
    loginResendUnavailable:
      'El reenvío de correo no está disponible actualmente. Por favor verifica tu bandeja de entrada y spam.',
    loginResendBtn: 'Reenviar correo de verificación (No disponible)',
    loginErrorTitle: 'Error de autenticación:',
    loginErrorDesc: 'Las credenciales proporcionadas no son válidas.',
    loginErrorHint:
      'Si acabas de registrarte, es posible que necesites verificar tu correo electrónico antes de poder iniciar sesión. Por favor revisa tu bandeja de entrada (incluyendo la carpeta de spam) y haz clic en el enlace de verificación.',

    // ScanQR
    scanCustomerQR: 'Escanear código QR del cliente',
    positionQR: 'Posiciona el código QR dentro del marco',
    cameraNotAvailable: 'Cámara no disponible',
    allowCameraAccess: 'Por favor permite el acceso a la cámara',
    scanLoadingStores: 'Cargando tiendas...',
    scanNoStoresTitle: 'Sin tiendas configuradas',
    scanNoStoresDesc: 'Necesitas tener al menos una tienda configurada para escanear códigos QR.',
    scanBackToDashboard: 'Volver al Dashboard',
    scanProcessing: 'Procesando...',
    scanReadingCard: 'Leyendo tarjeta...',
    scanMemberSince: 'Miembro desde',
    scanRewardReady: 'Premio listo para canjear',
    scanRedeemReward: 'Canjear Premio',
    scanStampsLabel: 'Sellos',
    scanAddingStamp: 'Agregando...',
    scanAddStamp: '+ Agregar Sello',
    scanStampAdded: '¡Sello Agregado!',
    scanRewardRedeemed: '¡Premio Canjeado!',
    scanRewardRedeemedSuccess: '¡Premio canjeado exitosamente!',
    scanClose: 'Cerrar',
    scanNewScan: 'Escanear Nuevo',
    scanRetry: 'Reintentar',
    scanSessionExpired: 'Tu sesión expiró. Por favor inicia sesión nuevamente.',
    scanCardNotFound: 'Tarjeta no encontrada',
    scanCardNotYours: 'Esta tarjeta no está registrada en tu negocio',
    scanCouldNotReadCard: 'No se pudo leer la tarjeta',
    scanCouldNotProcess: 'No se pudo procesar',
    scanErrorAddStamp: 'Error al agregar el sello',
    scanErrorRedeemReward: 'Error al canjear el premio',

    // Stores (dialogs & cards)
    storeNewStore: 'Nueva Sucursal',
    storeEditStore: 'Editar Sucursal',
    storeName: 'Nombre',
    storeNamePlaceholder: 'Ej. Centro',
    storeAddress: 'Dirección',
    storeAddressPlaceholder: 'Av. Principal 123',
    storeCity: 'Ciudad',
    storeCityPlaceholder: 'Ciudad de México',
    storeSaveChanges: 'Guardar Cambios',
    storeCreateStore: 'Crear Sucursal',
    storeNoStoresEmpty: 'No hay sucursales',
    storeNoStoresEmptyDesc: 'Aún no has creado ninguna sucursal. Usa el botón "Crear Sucursal" para comenzar.',
    storeDeleteDesc: 'Esta acción no se puede deshacer. Esto eliminará permanentemente la sucursal',
    storeDeleteDescSuffix: 'y todos sus datos asociados.',
    storeDeleting: 'Eliminando...',
    storeDelete: 'Eliminar',
    storeIdError: 'No se pudo obtener el ID de la sucursal',
    storeViewQr: 'Ver QR',
    storeQrTitle: 'QR de Sucursal',
    storeUrlUnavailable: 'URL no disponible',
    storeQrScanDesc: 'Escanea para ver los clubes disponibles',
    storeDownloadQr: 'Descargar QR',

    // Common (dialogs)
    confirmAreYouSure: '¿Estás seguro?',
    confirm: 'Confirmar',
    accept: 'Aceptar',
    delete: 'Eliminar',
    edit: 'Editar',
    linkCopied: 'Enlace copiado al portapapeles',
    linkCopyError: 'Error al copiar el enlace',
    members: 'miembros',

    // Customer Detail
    customerDetailTitle: 'Detalle del Cliente',
    customerJoined: 'Se unió:',
    customerPhone: 'Cel:',
    customerBirthday: 'Cumple:',
    customerSelectProgram: 'Seleccioná un programa',
    customerSelectProgramMetrics: 'Seleccioná un programa para ver las métricas',
    customerCurrentStamps: 'Sellos Actuales',
    customerTotalVisits: 'Visitas Totales',
    customerRewardsRedeemed: 'Premios Canjeados',
    customerProgressToReward: 'Progreso al próximo premio',
    customerPendingReward: 'Premio pendiente de canje',
    customerRedeemReward: 'Canjear Premio',
    customerHistory: 'Historial',
    customerStampAdded: 'Sello agregado',
    customerSelectStore: 'Seleccioná una sucursal',
    customerAddStampManually: 'Agregar Sello Manualmente',
    customerAdding: 'Agregando...',
    customerAddStampConfirmDesc: 'Estás a punto de agregar un sello manualmente a',
    customerAddStampConfirmSuffix: '. Esta acción no se puede deshacer.',
    customerStampDelivered: '¡Sello Entregado!',
    customerStampAddedTo: 'Se agregó un sello a',
    customerSelectStoreFirst: 'Seleccioná una sucursal antes de agregar el sello.',
    customerCardNotFound: 'No se encontró la tarjeta del cliente.',
    customerStampError: 'Error al agregar sello',
    customerRedeemError: 'Error al canjear el premio',
    customerRewardRedeemed: '¡Premio Canjeado!',

    // Program List
    programActive: 'Activa',
    programInactive: 'Inactiva',
    programPreview: 'Preview',
    programEdit: 'Editar',
    programViewQr: 'Ver QR',
    programShareLink: 'Compartir Link',
    programDelete: 'Eliminar',
    programDeleteDesc: 'Esta acción no se puede deshacer. Esto eliminará permanentemente el programa de lealtad',
    programDeleteDescSuffix: 'y todos sus datos asociados.',
    programQrTitle: 'QR del Programa',
    programQrOnly: 'Solo QR',
    programFlyerPrint: 'Flyer para Imprimir',
    programQrScanDesc: 'Escanea para unirte al programa de fidelidad',
    programCopyLink: 'Copiar Link',
    programDownloadQr: 'Descargar QR',
    programJoinShare: 'Únete a mi programa',
    programLoyaltyProgram: 'Programa de Fidelidad',

    // Flyer
    flyerTemplate: 'Plantilla',
    flyerClassic: 'Clásico',
    flyerMinimal: 'Minimal',
    flyerPromo: 'Promo',
    flyerTitle: 'Título',
    flyerSubtitle: 'Subtítulo',
    flyerSubtitlePlaceholder: 'Escanea y únete gratis',
    flyerReward: 'Recompensa',
    flyerRewardPlaceholder: 'Recompensa especial',
    flyerGenerating: 'Generando...',
    flyerDownload: 'Descargar Flyer',
    flyerDownloadNote: 'El flyer se descargará en PDF',
    flyerDownloadSuccess: 'Flyer descargado exitosamente',
    flyerDownloadError: 'Error al descargar el flyer',
    qrDownloadSuccess: 'QR descargado exitosamente',
    qrDownloadError: 'Error al descargar el QR',

    // CreateClub form (additional)
    formStores: 'Sucursales',
    formStoresDesc: 'Seleccioná las sucursales donde aplica este programa',
    formProgramType: 'Tipo de Club',
    formProgramTypePlaceholder: 'Selecciona el tipo de Club',
    formStampsType: 'Sellos',
    formInternalOnly: 'Solo para control interno',
    formCharacters: 'caracteres',
    formMaxStamps: 'Máximo 20 sellos',
    formBackgroundImage: 'Imagen de Fondo',
    formUploadBackground: 'Subir Imagen de Fondo',
    formStampImage: 'Imagen de Sello',
    formUploadStamp: 'Subir Imagen de Sello',
    formTextColor: 'Color de texto',
    formLabelColor: 'Color de etiqueta',
    formCustomerData: 'Datos a Solicitar al Cliente',
    formNameLabel: 'Nombre',
    formRequired: 'requerido',
    formRequestName: 'Solicitar nombre al cliente',
    formRequestEmail: 'Solicitar email al cliente',
    formPhoneLabel: 'Teléfono',
    formRequestPhone: 'Solicitar número de celular',
    formBirthdayLabel: 'Cumpleaños',
    formRequestBirthday: 'Solicitar fecha de nacimiento',
    formBusinessInfo: 'Datos de tu Negocio',

    // Date Filter
    dateFrom: 'Desde',
    dateTo: 'Hasta',

    // Hook toasts — useClubForm
    clubFormImageError: 'Error al procesar las imágenes. Intenta subirlas de nuevo.',
    clubFormImagesTooLarge:
      'Las imágenes son demasiado grandes. Intenta usar imágenes más pequeñas o de menor resolución.',
    clubFormUpdated: 'Programa actualizado exitosamente',
    clubFormUpdateError: 'Error al actualizar el programa',
    clubFormBackgroundRequired: 'Debes subir una imagen de fondo para la tarjeta',
    clubFormStampRequired: 'Debes subir una imagen para el sello',
    clubFormCreated: 'Programa creado exitosamente',
    clubFormCreateError: 'Error al crear el programa',
    clubFormImageProcessWarning: 'El programa se creó, pero hubo un problema al procesar las imágenes.',
    clubFormInvalidImageType: 'Por favor selecciona un archivo de imagen válido',
    clubFormFileTooLarge1MB: 'El archivo es demasiado grande. Máximo 1MB',
    clubFormFileTooLarge5MB: 'El archivo es demasiado grande. Máximo 5MB',
    clubFormLogoUploaded: 'Logo cargado correctamente',
    clubFormLogoProcessError: 'Error al procesar la imagen del logo',
    clubFormFileReadError: 'Error al leer el archivo',
    clubFormLogoUploadError: 'Error al cargar el logo',
    clubFormBackgroundUploaded: 'Imagen de fondo cargada correctamente',
    clubFormBackgroundProcessError: 'Error al procesar la imagen de fondo',
    clubFormStampUploaded: 'Imagen de sello cargada correctamente',
    clubFormStampProcessError: 'Error al procesar la imagen del sello',

    // Hook toasts — useDashboard
    dashboardLogoUpdated: 'Logo actualizado',
    dashboardLogoReadError: 'Error al leer la imagen',
    dashboardLogoUpdateError: 'Error al actualizar el logo',
    dashboardBrandDeleted: 'Marca eliminada exitosamente',
    dashboardBrandDeleteError: 'Error al eliminar la marca',

    // Hook toasts — useStores
    storeCreated: 'Sucursal creada exitosamente',
    storeCreateError: 'Error al crear la sucursal',
    storeUpdated: 'Sucursal actualizada exitosamente',
    storeUpdateError: 'Error al actualizar la sucursal',
    storeDeleted: 'Sucursal eliminada exitosamente',
    storeDeleteError: 'Error al eliminar la sucursal',
    storeAuthError: 'Error de autenticación. Por favor, recarga la página.',

    // Hook toasts — useMyPrograms
    programActivated: 'Programa activado',
    programDeactivated: 'Programa desactivado',
    programToggleError: 'Error al cambiar estado del programa',
    programDeleted: 'Programa eliminado exitosamente',
    programDeleteError: 'Error al eliminar el programa',
  },
  en: {
    // Navigation & Layout
    dashboard: 'Dashboard',
    myPrograms: 'My Programs',
    customers: 'Members',
    stores: 'Stores',
    notifications: 'Notifications',
    comingSoon: 'Coming Soon',
    team: 'Team',
    createProgram: 'Create Program',
    profile: 'Profile',
    logout: 'Log Out',
    survey: 'Survey',
    menu: 'Menu',

    // Common / Shared
    search: 'Search...',
    welcome: 'Welcome',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    actions: 'Actions',
    goBack: 'Go Back',
    change: 'Change',
    days: 'Days',
    active: 'Active',
    showing: 'Showing',
    of: 'of',
    sortBy: 'Sort by',
    sortByDate: 'Registration date',
    sortByVisits: 'Total visits',

    // Sidebar
    support: 'Support',
    logoutSuccess: 'Logged out successfully',
    logoutError: 'Error logging out',

    // Dashboard
    dashboardSubtitle: 'Check your loyalty program statistics',
    dashboardLoadError: 'Error loading dashboard',
    programMembers: 'Program Members',
    activePrograms: 'Active Programs',
    stamps: 'Stamps',
    rewards: 'Rewards',
    redemptionRate: 'Redemption Rate',
    thisWeek: 'this week',
    membersChartTitle7d: 'Members (Last 7 days)',
    membersChartTitleMonth: 'Members (This Month)',
    membersChartTitle: 'Members',
    stampsChartTitle: 'Stamps Given',
    rewardsChartTitle: 'Rewards Given',
    stampsDistributionTitle: 'Stamps Distribution',
    stampsDistributionSubtitle: 'Members grouped by stamp count',
    stampSingular: 'stamp',
    stampPlural: 'stamps',

    // Filters (shared across pages)
    filterStore: 'Filter by Store',
    filterPeriod: 'Select period',
    periodDefault: 'Default',
    period7d: 'Last 7 days',
    periodMonth: 'This Month',
    periodCustom: 'Custom',
    allTime: 'All time',
    pickDate: 'Pick a date',
    filterMonth: 'Filter by month',
    filterProgram: 'Filter by program',
    filterStamps: 'Filter by stamps',
    allMonths: 'All Months',
    allPrograms: 'All Programs',
    allStamps: 'All',

    // Stores
    store: 'Store',
    allStores: 'All Stores',
    storesTitle: 'Stores',
    storesSubtitle: 'Manage your business locations',
    accessDenied: 'Access Denied. Admins only.',
    selectLocation: 'Select Location',
    whereWorking: 'Where are you working today?',
    chooseStore: 'Choose a store...',

    // MyPrograms
    myProgramsSubtitle: 'Manage your Loyalty Programs',
    searchPrograms: 'search programs...',
    noProgramsTitle: 'No programs yet',
    noProgramsDesc: 'Start by creating your first loyalty program',
    noProgramsForStore: 'No programs in this store',
    noProgramsForStoreDesc: 'No programs were found associated with the selected store',
    createFirstProgram: 'Create your first program',

    // Customers
    customersSubtitle: 'Users who added your loyalty programs to their wallet',
    searchEmail: 'Search by email...',
    showingCustomers: 'Showing',
    customersCount: 'members',
    noCustomersTitle: 'No members found',
    noCustomersDesc: "When users add your programs to their wallet, they'll appear here",
    unknownProgram: 'Unknown Program',
    noEmail: 'No email',
    stamp: 'Stamp',

    // CreateClub form
    backToPrograms: 'Back to Programs',
    editProgram: 'Edit Program',
    createNewProgram: 'Create New Program',
    livePreview: 'Live Preview',
    livePreviewDesc: 'See how your program will look',
    clubName: 'Club Name',
    clubNamePlaceholder: 'e.g., Points Club',
    programTitle: 'Program Title',
    programTitlePlaceholder: 'e.g., Loyalty Rewards',
    description: 'Description',
    descriptionPlaceholder: 'Describe your loyalty program...',
    rewardOffer: 'Reward Offer',
    rewardOfferPlaceholder: 'e.g., Buy 10, Get 1 Free',
    stampsRequired: 'Stamps Required',
    logo: 'Logo',
    uploadLogo: 'Upload Logo',
    primaryColor: 'Primary Color',
    gradientColor: 'Gradient Color',
    contactEmail: 'Contact Email',
    contactPhone: 'Contact Phone',
    website: 'Website',
    termsAndConditions: 'Terms & Conditions',
    termsPlaceholder: 'Enter terms and conditions...',
    updateProgram: 'Update Program',
    createProgramBtn: 'Create Program',
    securityAndFraud: 'Security & Fraud',
    validityAndTerms: 'Validity & Terms',
    requireTicket: 'Require Purchase Ticket',
    requireTicketDesc: 'Request ticket number and amount when giving stamps',
    locationValidation: 'Location Validation',
    locationValidationDesc: 'Only allow giving stamps within the store',
    cooldownTime: 'Cooldown between stamps (hours)',
    cooldownTimeDesc: 'Prevent same customer from getting multiple stamps in short time',
    noTimeLimit: '0 = No limit',
    stampsValidity: 'Time to collect stamps',
    rewardValidity: 'Time to redeem reward',
    programValidity: 'Program validity',
    alwaysActive: '0 = Always active',

    // Profile
    manageAccount: 'Manage your account and subscription',
    programsCreated: 'Programs Created',
    assignedStore: 'Assigned Store',
    unassigned: 'Unassigned',
    password: 'Password',
    changePassword: 'Change Password',
    language: 'Language',
    selectLanguage: 'Select Language',
    role: 'Role',
    admin: 'Admin',
    employee: 'Employee',

    // Subscription
    subscription: 'Subscription',
    freePlan: 'Free Plan',
    planFeature1: 'Up to 5 loyalty programs',
    planFeature2: 'Basic analytics',
    planFeature3: 'Standard support',
    upgradePlan: 'Upgrade Plan',

    // Team
    manageTeamDesc: 'Manage user roles and store access',

    // Notifications
    notificationsDescription: 'Send push notifications to users who added your cards to their wallet',
    notificationProgram: 'Program',
    notificationAllPrograms: 'All programs',
    notificationHeader: 'Header',
    notificationHeaderPlaceholder: 'e.g., Special offer!',
    notificationBody: 'Message',
    notificationBodyPlaceholder: 'e.g., Visit us today and get double stamps',
    notificationSend: 'Send notification',
    notificationSent: 'Notification sent successfully',
    notificationError: 'Error sending notification',
    notificationInfo:
      'The notification will be sent to all users with cards in Google Wallet. Apple Wallet users will receive a silent update.',

    // Login & Auth
    loginTitle: 'Sign In',
    loginCreateAccount: 'Create Account',
    loginWelcomeBack: 'Welcome back',
    loginStartJourney: 'Start your journey with us',
    loginContinueWithEmail: 'Continue with your email',
    loginName: 'Name',
    loginNamePlaceholder: 'Your full name',
    loginForgotPassword: 'Forgot your password?',
    loginMinChars: 'At least 8 characters',
    loginUppercase: 'At least one uppercase letter',
    loginNumber: 'At least one number',
    loginSigningIn: 'Signing in...',
    loginCreatingAccount: 'Creating account...',
    loginNoAccount: "Don't have an account? ",
    loginHaveAccount: 'Already have an account? ',
    loginRegister: 'Sign Up',
    loginSuccessToast: 'Login successful!',
    loginAuthError: 'Authentication error. Please try again.',
    loginInvalidCredentials: 'Invalid credentials. Please try again.',
    loginNetworkError: 'Connection error. Check your internet and try again.',
    loginVerifyEmail: 'Please verify your email before signing in',
    loginRegisterSuccess: 'Registration successful! Please verify your email.',
    loginRegisterError: 'Error registering',
    loginError: 'Error signing in',
    loginShowPassword: 'Show password',
    loginHidePassword: 'Hide password',
    loginVerificationSent: 'A verification email has been sent to',
    loginVerificationCheck: 'Please check your inbox (and spam folder) and click the link to activate your account.',
    loginVerificationSpam:
      "If you don't receive the email in a few minutes, check your spam folder or contact the administrator.",
    loginResendUnavailable: 'Email resend is not available at this time. Please check your inbox and spam folder.',
    loginResendBtn: 'Resend verification email (Unavailable)',
    loginErrorTitle: 'Authentication error:',
    loginErrorDesc: 'The provided credentials are not valid.',
    loginErrorHint:
      'If you just registered, you may need to verify your email before signing in. Please check your inbox (including spam folder) and click the verification link.',

    // ScanQR
    scanCustomerQR: "Scan customer's QR code",
    positionQR: 'Position the QR code within the frame',
    cameraNotAvailable: 'Camera not available',
    allowCameraAccess: 'Please allow camera access to scan QR codes',
    scanLoadingStores: 'Loading stores...',
    scanNoStoresTitle: 'No stores configured',
    scanNoStoresDesc: 'You need at least one store configured to scan QR codes.',
    scanBackToDashboard: 'Back to Dashboard',
    scanProcessing: 'Processing...',
    scanReadingCard: 'Reading card...',
    scanMemberSince: 'Member since',
    scanRewardReady: 'Reward ready to redeem',
    scanRedeemReward: 'Redeem Reward',
    scanStampsLabel: 'Stamps',
    scanAddingStamp: 'Adding...',
    scanAddStamp: '+ Add Stamp',
    scanStampAdded: 'Stamp Added!',
    scanRewardRedeemed: 'Reward Redeemed!',
    scanRewardRedeemedSuccess: 'Reward redeemed successfully!',
    scanClose: 'Close',
    scanNewScan: 'Scan New',
    scanRetry: 'Retry',
    scanSessionExpired: 'Your session expired. Please sign in again.',
    scanCardNotFound: 'Card not found',
    scanCardNotYours: 'This card is not registered to your business',
    scanCouldNotReadCard: 'Could not read the card',
    scanCouldNotProcess: 'Could not process',
    scanErrorAddStamp: 'Error adding stamp',
    scanErrorRedeemReward: 'Error redeeming reward',

    // Stores (dialogs & cards)
    storeNewStore: 'New Store',
    storeEditStore: 'Edit Store',
    storeName: 'Name',
    storeNamePlaceholder: 'e.g., Downtown',
    storeAddress: 'Address',
    storeAddressPlaceholder: '123 Main Street',
    storeCity: 'City',
    storeCityPlaceholder: 'New York',
    storeSaveChanges: 'Save Changes',
    storeCreateStore: 'Create Store',
    storeNoStoresEmpty: 'No stores yet',
    storeNoStoresEmptyDesc: 'You haven\'t created any stores yet. Use the "Create Store" button to get started.',
    storeDeleteDesc: 'This action cannot be undone. This will permanently delete the store',
    storeDeleteDescSuffix: 'and all its associated data.',
    storeDeleting: 'Deleting...',
    storeDelete: 'Delete',
    storeIdError: 'Could not get the store ID',
    storeViewQr: 'View QR',
    storeQrTitle: 'Store QR',
    storeUrlUnavailable: 'URL not available',
    storeQrScanDesc: 'Scan to see available programs',
    storeDownloadQr: 'Download QR',

    // Common (dialogs)
    confirmAreYouSure: 'Are you sure?',
    confirm: 'Confirm',
    accept: 'Accept',
    delete: 'Delete',
    edit: 'Edit',
    linkCopied: 'Link copied to clipboard',
    linkCopyError: 'Error copying link',
    members: 'members',

    // Customer Detail
    customerDetailTitle: 'Customer Detail',
    customerJoined: 'Joined:',
    customerPhone: 'Phone:',
    customerBirthday: 'Birthday:',
    customerSelectProgram: 'Select a program',
    customerSelectProgramMetrics: 'Select a program to see metrics',
    customerCurrentStamps: 'Current Stamps',
    customerTotalVisits: 'Total Visits',
    customerRewardsRedeemed: 'Rewards Redeemed',
    customerProgressToReward: 'Progress to next reward',
    customerPendingReward: 'Pending reward redemption',
    customerRedeemReward: 'Redeem Reward',
    customerHistory: 'History',
    customerStampAdded: 'Stamp added',
    customerSelectStore: 'Select a store',
    customerAddStampManually: 'Add Stamp Manually',
    customerAdding: 'Adding...',
    customerAddStampConfirmDesc: 'You are about to manually add a stamp to',
    customerAddStampConfirmSuffix: '. This action cannot be undone.',
    customerStampDelivered: 'Stamp Delivered!',
    customerStampAddedTo: 'A stamp was added to',
    customerSelectStoreFirst: 'Please select a store before adding a stamp.',
    customerCardNotFound: 'Customer card not found.',
    customerStampError: 'Error adding stamp',
    customerRedeemError: 'Error redeeming reward',
    customerRewardRedeemed: 'Reward Redeemed!',

    // Program List
    programActive: 'Active',
    programInactive: 'Inactive',
    programPreview: 'Preview',
    programEdit: 'Edit',
    programViewQr: 'View QR',
    programShareLink: 'Share Link',
    programDelete: 'Delete',
    programDeleteDesc: 'This action cannot be undone. This will permanently delete the loyalty program',
    programDeleteDescSuffix: 'and all its associated data.',
    programQrTitle: 'Program QR',
    programQrOnly: 'QR Only',
    programFlyerPrint: 'Printable Flyer',
    programQrScanDesc: 'Scan to join the loyalty program',
    programCopyLink: 'Copy Link',
    programDownloadQr: 'Download QR',
    programJoinShare: 'Join my program',
    programLoyaltyProgram: 'Loyalty Program',

    // Flyer
    flyerTemplate: 'Template',
    flyerClassic: 'Classic',
    flyerMinimal: 'Minimal',
    flyerPromo: 'Promo',
    flyerTitle: 'Title',
    flyerSubtitle: 'Subtitle',
    flyerSubtitlePlaceholder: 'Scan and join for free',
    flyerReward: 'Reward',
    flyerRewardPlaceholder: 'Special reward',
    flyerGenerating: 'Generating...',
    flyerDownload: 'Download Flyer',
    flyerDownloadNote: 'The flyer will be downloaded as PDF',
    flyerDownloadSuccess: 'Flyer downloaded successfully',
    flyerDownloadError: 'Error downloading flyer',
    qrDownloadSuccess: 'QR downloaded successfully',
    qrDownloadError: 'Error downloading QR',

    // CreateClub form (additional)
    formStores: 'Stores',
    formStoresDesc: 'Select the stores where this program applies',
    formProgramType: 'Program Type',
    formProgramTypePlaceholder: 'Select the program type',
    formStampsType: 'Stamps',
    formInternalOnly: 'Internal use only',
    formCharacters: 'characters',
    formMaxStamps: 'Maximum 20 stamps',
    formBackgroundImage: 'Background Image',
    formUploadBackground: 'Upload Background Image',
    formStampImage: 'Stamp Image',
    formUploadStamp: 'Upload Stamp Image',
    formTextColor: 'Text Color',
    formLabelColor: 'Label Color',
    formCustomerData: 'Customer Data to Collect',
    formNameLabel: 'Name',
    formRequired: 'required',
    formRequestName: 'Request customer name',
    formRequestEmail: 'Request customer email',
    formPhoneLabel: 'Phone',
    formRequestPhone: 'Request phone number',
    formBirthdayLabel: 'Birthday',
    formRequestBirthday: 'Request date of birth',
    formBusinessInfo: 'Business Information',

    // Date Filter
    dateFrom: 'From',
    dateTo: 'To',

    // Hook toasts — useClubForm
    clubFormImageError: 'Error processing images. Please try uploading them again.',
    clubFormImagesTooLarge: 'Images are too large. Try using smaller or lower resolution images.',
    clubFormUpdated: 'Program updated successfully',
    clubFormUpdateError: 'Error updating program',
    clubFormBackgroundRequired: 'You must upload a background image for the card',
    clubFormStampRequired: 'You must upload a stamp image',
    clubFormCreated: 'Program created successfully',
    clubFormCreateError: 'Error creating program',
    clubFormImageProcessWarning: 'The program was created, but there was an issue processing the images.',
    clubFormInvalidImageType: 'Please select a valid image file',
    clubFormFileTooLarge1MB: 'File is too large. Maximum 1MB',
    clubFormFileTooLarge5MB: 'File is too large. Maximum 5MB',
    clubFormLogoUploaded: 'Logo uploaded successfully',
    clubFormLogoProcessError: 'Error processing logo image',
    clubFormFileReadError: 'Error reading file',
    clubFormLogoUploadError: 'Error uploading logo',
    clubFormBackgroundUploaded: 'Background image uploaded successfully',
    clubFormBackgroundProcessError: 'Error processing background image',
    clubFormStampUploaded: 'Stamp image uploaded successfully',
    clubFormStampProcessError: 'Error processing stamp image',

    // Hook toasts — useDashboard
    dashboardLogoUpdated: 'Logo updated',
    dashboardLogoReadError: 'Error reading image',
    dashboardLogoUpdateError: 'Error updating logo',
    dashboardBrandDeleted: 'Brand deleted successfully',
    dashboardBrandDeleteError: 'Error deleting brand',

    // Hook toasts — useStores
    storeCreated: 'Store created successfully',
    storeCreateError: 'Error creating store',
    storeUpdated: 'Store updated successfully',
    storeUpdateError: 'Error updating store',
    storeDeleted: 'Store deleted successfully',
    storeDeleteError: 'Error deleting store',
    storeAuthError: 'Authentication error. Please reload the page.',

    // Hook toasts — useMyPrograms
    programActivated: 'Program activated',
    programDeactivated: 'Program deactivated',
    programToggleError: 'Error changing program status',
    programDeleted: 'Program deleted successfully',
    programDeleteError: 'Error deleting program',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('es')
  const [isLoaded, setIsLoaded] = useState(false)

  useEffect(() => {
    // Load initial language from user profile if available, or local storage
    const loadLanguage = () => {
      try {
        const user = getCurrentUser()
        if (user?.language) {
          setLanguage(user.language)
        } else {
          const saved = localStorage.getItem('app_language')
          if (saved) setLanguage(saved)
        }
      } catch {
        // User not logged in or error
        const saved = localStorage.getItem('app_language')
        if (saved) setLanguage(saved)
      } finally {
        setIsLoaded(true)
      }
    }
    loadLanguage()
  }, [])

  const changeLanguage = async (lang) => {
    setLanguage(lang)
    localStorage.setItem('app_language', lang)
    // Nota: api.auth.updateMe() no existe en el backend según el YAML
    // El idioma se guarda solo en localStorage hasta que el backend implemente PATCH /auth/me
    // try {
    //    await api.auth.updateMe({ language: lang });
    // } catch (e) {
    //   console.error("Failed to save language preference", e);
    // }
  }

  const t = (key) => translations[language][key] || key

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, isLoaded }}>{children}</LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
